// src/components/layout/AppLayout.tsx
import { Outlet } from 'react-router-dom'
import { AppHeader } from './AppHeader'
import { AppFooter } from './AppFooter'
import './AppLayout.scss'

export default function AppLayout() {
  return (
    <div className="app-layout">
      <AppHeader />
      <main className="main-content">
        <Outlet />
      </main>
      <AppFooter />
    </div>
  )
}

// src/components/layout/AppLayout.vue
<template>
  <div class="app-layout">
    <AppHeader />
    <main class="main-content">
      <router-view />
    </main>
    <AppFooter />
  </div>
</template>

<script>
import AppHeader from './AppHeader.vue'
import AppFooter from './AppFooter.vue'

export default {
  name: 'AppLayout',
  components: {
    AppHeader,
    AppFooter
  }
}
</script>

<style scoped>
.app-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.main-content {
  flex: 1;
  padding-top: 120px; /* Space for fixed header */
  min-height: calc(100vh - 120px);
}
</style>
